### ISSUE TITLE
Error: 404 status code downloading tarball https://github.com/idan-at/native-sizeof/releases/download/0.1.4/node-v93-linux-x64.tar.gz

### ISSUE THREAD

**Issue by tukusejssirs** [idan-at/native-sizeof#1]
I use `node@16.13.2` and `npm@8.1.2`.

When I try to install the package (`npm i native-sizeof`), it fails to do so:

```bash
npm WARN deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 127
npm ERR! path /home/ts/git/itens/otto/controlserver/node_modules/native-sizeof
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build=false || npm run build
npm ERR! 404 status code downloading tarball https://github.com/idan-at/native-sizeof/releases/download/0.1.4/node-v93-linux-x64.tar.gz
npm ERR! 
npm ERR! > native-sizeof@0.1.4 build
npm ERR! > neon build --release
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.17.0
npm ERR! node-pre-gyp info using node@16.13.2 | linux | x64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/home/ts/git/itens/otto/controlserver/node_modules/native-sizeof/native/index.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/idan-at/native-sizeof/releases/download/0.1.4/node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/idan-at/native-sizeof/releases/download/0.1.4/node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/idan-at/native-sizeof/releases/download/0.1.4/node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/home/ts/git/itens/otto/controlserver/node_modules/node-pre-gyp/lib/install.js:142:27)
npm ERR! node-pre-gyp ERR! stack     at PassThrough.emit (node:events:402:35)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/home/ts/git/itens/otto/controlserver/node_modules/needle/lib/needle.js:538:9)
npm ERR! node-pre-gyp ERR! stack     at Object.onceWrapper (node:events:510:26)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:623:27)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:487:22)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:315:12)
npm ERR! node-pre-gyp ERR! System Linux 5.16.2-arch1-1
npm ERR! node-pre-gyp ERR! command "/home/ts/.nvm/versions/node/v16.13.2/bin/node" "/home/ts/git/itens/otto/controlserver/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
npm ERR! node-pre-gyp ERR! cwd /home/ts/git/itens/otto/controlserver/node_modules/native-sizeof
npm ERR! node-pre-gyp ERR! node -v v16.13.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.17.0
npm ERR! node-pre-gyp ERR! not ok 
npm ERR! sh: line 1: neon: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ts/.npm/_logs/2022-01-26T09_56_29_569Z-debug.log
```

The thing is, it tries to download `node-v93-linux-x64.tar.gz`, which (looking at the [assets of `v0.1.4`](https://github.com/idan-at/native-sizeof/releases/tag/0.1.4)) does not exist.

One way to solve this is to create it, however, what’s the purpose of dividing the package by `node` versions? Are there some incompatibilities? Or this way you can make the package more performant?

**Comment by idan-at** [comment]
Hey,

Since this is a native package, it has to be built for every node version separately.
I remember I had issues with node 16, but I don't remember what exactly.

I've opened a PR to see if it works: https://github.com/idan-at/native-sizeof/pull/2

**Comment by tukusejssirs** [comment]
While at it, could you also release a version for v17? :wink:

**Comment by tukusejssirs** [comment]
Anyway, I tried to use `node@v15.14.0` with `npm@7.7.6`, but it didn’t work either. I tried to download `node-v88-linux-x64.tar.gz`.

**Comment by idan-at** [comment]
I just merged the PR that will also build on node 16.
LMK if it works for you (make sure [all the actions](https://github.com/idan-at/native-sizeof/runs/4950161584?check_suite_focus=true) pass before you do)

If so, I'll also release a version for 17 :)

**Comment by tukusejssirs** [comment]
All tests pass, but it does not publish a new version (`publish` step seems to be skipped), therefore `npm i native-sizeof` still fails (maybe that is intended).

Do I need to build it locally and use that build in order to test the latest commit? Or is there other way? :wink:

**Comment by idan-at** [comment]
I'm sorry, the publish step didn't run on this action.
I tried running it, but it fails on node 16.

Related issue is here: https://github.com/bchr02/node-pre-gyp-github/issues/34

Let's see if they can fix this library. if not, I'll find an alternative

**Comment by tukusejssirs** [comment]
Thanks for trying to fix it. :pray:

As I see it, `node-pre-gyp-github` seems to be rather unmaintained (latest commit merged into `master` is from 1 December 2018) and the package owner didn’t react on the issues created approx since then.

Therefore I suggest to replace this dependency.

**Comment by idan-at** [comment]
node 16 should work (I tried it on my machine)

Will do 17 in a few minutes

**Comment by tukusejssirs** [comment]
Thanks, @idan-at! Now working as expected! :pray:
